config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => 'sessions', :omniauth_callbacks => 'omniauth_callbacks' } do
  end

  root to: 'home#index'

  get '/client', to: 'client/chats#index'

  namespace :client do
    get '/chats/configure/:chat_id', to: 'chats#configure', as: 'chats_configure'

    resources :chats, only: [:index] do
      get '/trello', to: 'trello#index'
      post '/trello/webhook_enabled', to: 'trello#webhook_enabled'
      post '/trello/webhook_disabled', to: 'trello#webhook_disabled'

      namespace :github do
        get '/setup_webhook_howto', to: 'repositories#setup_webhook_howto'
        post '/repositories/:id', to: 'repositories#update'

        resources :repositories, only: [:index, :show]
      end

      namespace :gitlab do
        resources :repositories, only: [:index, :show]
      end
    end
  end

  namespace :webhooks do
    post '/github/:chat_id', to: 'github#callback', as: 'github'
    post '/gitlab/:chat_id', to: 'gitlab#callback', as: 'gitlab'

    get '/trello/:chat_id', to: 'trello#callback_get', as: 'trello_get'
    post '/trello/:chat_id', to: 'trello#callback', as: 'trello'
  end

end

app/controllers/client/github/repositories_controller.rb
class Client::Github::RepositoriesController < ClientController
  before_action :load_chat

  def index
      @user_repos = @github_service.user_repos
      @org_repos = @github_service.org_repos

      repo_names = @org_repos.map {|x| x.full_name }
      repo_names += @user_repos.map {|x| x.full_name }

      # add ones we know about but which wasn't returned by Github
      @org_repos += @chat.github_repos.select {|gr|
        not (repo_names.include? gr.name)
      }
  end

  def show
    @id = params[:id]
    @github_repo = @chat.find_github_repo @id
  end

  def update
    @id = params[:id]
    enabled = @chat.github_repo_enabled? @id

    if not enabled and params[:enabled]
      if @github_service.create_hook @id, @chat
        flash[:success] = 'Web hook created!'
      else
        flash[:error] = 'You need to grant access to Hackwrench Bot on this repo or organization on GitHub.'
      end

    elsif enabled and not params[:enabled]
      @github_service.delete_hook @id, @chat

      flash[:success] = 'Web hook removed.'
    end

    redirect_to action: 'show'
  end

  def setup_webhook_howto
    @chat = Chat.find_by chat_id: params[:chat_id]
    @callback_url = GithubService.new(current_user.github_token).callback_url @chat
  end
end

app/controllers/client/gitlab/repositories_controller.rb
class Client::Gitlab::RepositoriesController < ClientController
  before_action :load_chat

  def index
    @repos = @chat.gitlab_repos
    @callback_url = GitlabService.callback_url @chat
  end
end

app/controllers/webhooks/github_controller.rb
class Webhooks::GithubController < ApplicationController
  protect_from_forgery with: :null_session

  def callback
    chat = Chat.find_by(chat_id: params[:chat_id])

    event_type = request.headers['X-GitHub-Event']
    guid = request.headers['X-GitHub-Delivery']
    body = request.body.read()
    body = body.blank? ? {} : JSON.parse(body)

    Rails.logger.info "github callback telegram_chat_id=#{chat.telegram_chat_id} event_type=#{event_type} guid=#{guid} body=#{body}"

    create_repo_if_needed chat, body

    case event_type
      when 'push'
        push_event chat, body
      when 'issues'
        issues_event chat, body
      when 'issue_comment'
        comment_issue chat, body
      when 'pull_request'
        pull_request chat, body
    end

    chat.increment_github_events

    render nothing: true
  end

  protected

  def push_event(chat, body)
    if body['commits'].length > 1
      msg = '%s pushed %d commits to %s %s'
    else
      msg = '%s pushed %d commit to %s %s'
    end

    branch = body['ref'].split('/').last

    msg = msg % [body['pusher']['name'], body['commits'].length, branch, body['compare']]
    body['commits'].each do |commit|
      title = commit['message'].split("\n",2).first
      msg += "\n%s - %s" % [commit['id'][0..5], title]
    end
    msg = repo_msg(body, msg)

    ChatService.new.send_update(chat, msg)
  end

  def issues_event(chat, body)
    msg = repo_msg(body, "issue \"#{body['issue']['title']}\" #{body['action']} by #{body['sender']['login']} #{body['issue']['html_url']}")
    ChatService.new.send_update chat, msg
  end

  def comment_issue(chat, body)
    # do not send it for now
  end

  def pull_request(chat, body)
    msg = repo_msg(body, "pull request #{body['action']} by #{body['sender']['login']} #{body['pull_request']['html_url']}")
    ChatService.new.send_update chat, msg
  end

  def repo_msg(body, msg)
    return "#{body['repository']['full_name']}: #{msg}"
  end

  # if webhook set up manually, we aren't aware of repo yet
  def create_repo_if_needed(chat, body)
    repo = body['repository']

    if repo.nil?
      return
    end

    repo_name = repo['full_name']

    if chat.find_github_repo(repo_name).nil?
      chat.create_github_repo(repo_name, created_on_webhook: true)
      # GitHub sends ping event to webhook on creation, let's notify the chat about newly
      # added repository
      GithubService.webhook_enabled(chat, repo_name)
    end
  end
end

app/views/client/github/repositories/_repo_list_item.html.slim
a.list-group-item(href=client_chat_github_repository_path(@chat.chat_id, repo.full_name))
  '#{repo.full_name.sub('/', ' / ')}
  - if @chat.github_repo_enabled? repo.full_name
    span.badge.green enabled
  - else
    span.badge disabled

  - if repo.try(:created_on_webhook)
    span.badge.info configured manually

app/views/client/github/repositories/index.html.slim
h2 Your GitHub repos

- if @user_repos && @user_repos.length > 0
  .list-group
    - for repo in @user_repos
      = render 'client/github/repositories/repo_list_item', repo: repo
- else
  p No repos found.

h2 Org and private Github repos

- if @org_repos && @org_repos.length > 0
  .list-group
    - for repo in @org_repos
      = render 'client/github/repositories/repo_list_item', repo: repo
- else
  p No repos found.

p.lead
  'Don't see your repo?
  = link_to 'Configure', client_chat_github_setup_webhook_howto_path(@chat.chat_id)
  '
  'it manually.

app/views/client/github/repositories/setup_webhook_howto.html.slim
p
  = link_to 'Back to repos', client_chat_github_repositories_path(@chat.chat_id)

h2 How to setup notifications manually

p Hey, we don't want to access your private data. If you want to get notifications about events in your private repos, follow this guide.

p &nbsp;

p
  'Go to
  strong> Webhooks & services settings
  'of your repo. Click on
  strong Add webhook
  '.

p
  = image_tag('setup_webhook_howto/repo_settings_small.jpg', class: 'instruction-img')

p &nbsp;

p Fill the form

dl.dl-horizontal.dl-horizontal-webhook-te
  dt Payload URL
  dd
    = @callback_url
  dt Content type
  dd application/json

p Then select the events that you'd like to trigger notifications.

p
  = image_tag('setup_webhook_howto/create_webhook_small.jpg', class: 'instruction-img')

p
  'Save. The repo should appear in
  = link_to 'the list', client_chat_github_repositories_path(@chat.chat_id)
  '.

app/views/client/github/repositories/show.html.slim
/- if @our_hook
/  = @our_hook.to_yaml

p
  = link_to 'Back to repos', client_chat_github_repositories_path(@chat.chat_id)

h2 GitHub repo #{@id}

p &nbsp;

- if @github_repo && @github_repo.created_on_webhook
  - if @github_repo.disabled
    p
      'Follow
      = link_to 'the guide', client_chat_github_setup_webhook_howto_path(@chat.chat_id)
      '
      'to enable notifications from this repo.
  - else
    p This repo has notifications enabled. They can be managed in repo webhook settings.
- else
  = form_tag(controller: 'client/github/repositories', action: 'update', id: @id)
    .checkbox
      label
        = check_box_tag('enabled', '1', @chat.github_repo_enabled?(@id))
        - if @github_repo && @github_repo.created_on_webhook
          'Enabled notifications (all configured events in Github will cause a notification)
        - else
          'Enable notifications about
          strong> pushes, issues and pull requests
          'in the chat "#{@chat.title}"
    = submit_tag('Save', class: 'btn btn-default')