config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => 'sessions', :omniauth_callbacks => 'omniauth_callbacks' } do
  end

  root to: 'home#index'

  get '/client', to: 'client/chats#index'

  namespace :client do
    get '/chats/configure/:chat_id', to: 'chats#configure', as: 'chats_configure'

    resources :chats, only: [:index] do
      get '/trello', to: 'trello#index'
      post '/trello/webhook_enabled', to: 'trello#webhook_enabled'
      post '/trello/webhook_disabled', to: 'trello#webhook_disabled'

      namespace :github do
        get '/setup_webhook_howto', to: 'repositories#setup_webhook_howto'
        post '/repositories/:id', to: 'repositories#update'

        resources :repositories, only: [:index, :show]
      end

      namespace :gitlab do
        resources :repositories, only: [:index, :show]
      end
    end
  end

  namespace :webhooks do
    post '/github/:chat_id', to: 'github#callback', as: 'github'
    post '/gitlab/:chat_id', to: 'gitlab#callback', as: 'gitlab'

    get '/trello/:chat_id', to: 'trello#callback_get', as: 'trello_get'
    post '/trello/:chat_id', to: 'trello#callback', as: 'trello'
  end

end

app/views/layouts/client.html.slim
doctype 5
html ng-app='ClientApp'
  head
    meta charset="UTF-8"
    meta http-equiv="Content-Type" content="text/html; charset=utf-8"

    title
      = t('hackwrench.home_page.title')
    link rel="shortcut icon" href="/favicon.ico"

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'client'
    = csrf_meta_tags
  body
    #wrap-te
      #main-te
        .navbar.navbar-te
          .navbar-inner
            .container.clearfix
              ul.nav.navbar-nav
                li.chats(class="#{'active' if controller.class.name.include? 'Chats'}")
                  a(href="#{client_chats_path}")
                    'select chat

                - if @chat.present?
                  li(class="#{'active' if controller.class.name.include? 'Github'}")
                    = link_to 'Github', client_chat_github_repositories_path(@chat.chat_id)

                  li(class="#{'active' if controller.class.name.include? 'Gitlab'}")
                    = link_to 'Gitlab', client_chat_gitlab_repositories_path(@chat.chat_id)

                  li(class="#{'active' if controller.class.name.include? 'Trello'}")
                    = link_to 'Trello', client_chat_trello_path(@chat.chat_id)

              ul.nav.navbar-nav.navbar-right
                - if @chat.present?
                  li
                    .current-user
                      = @chat.title
                li
                  = link_to('Logout', destroy_user_session_path, :method => :delete)

        .page-te
          .container
            = render '/flash_message'

            = yield

    footer.footer-te
      .container
        = render '/footer_text'

    = render '/ga'
    = render '/github_button_script'

app/views/layouts/home.html.slim
doctype 5
html
  head
    meta charset="UTF-8"
    meta http-equiv="Content-Type" content="text/html; charset=utf-8"

    title
      = t('hackwrench.home_page.title')
    link rel="shortcut icon" href="/favicon.ico"

    meta name="description" content="#{t('hackwrench.home_page.meta.description')}"

    link rel="canonical" href="http://hackwrench.us"
    link rel="shortlink" href="http://hackwrench.us"

    meta property="og:site_name" content="hackwrench.us"
    meta property="og:type" content="website"
    meta property="og:url" content="#{request.original_url}"
    meta property="og:title" content="#{t('hackwrench.home_page.title')}"
    meta property="og:description" content="#{t('hackwrench.home_page.meta.description')}"

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

    = render '/ga'
  body
    #wrap-te
      #main-te
        .navbar.navbar-te
          .navbar-inner
            .container.clearfix
              ul.nav.navbar-nav
                li.active
                  = link_to 'Home', root_path
              - if user_signed_in?
                ul.nav.navbar-nav.navbar-right
                  li
                    .current-user Signed in as #{current_user.name}
                  li
                    = link_to('Logout', destroy_user_session_path, :method => :delete)
              - else
                ul.nav.navbar-nav.navbar-right
                  li.login-with-github
                    a(href=omniauth_authorize_path(:user, 'github'))
                      |Login with
                      = image_tag('GitHub-Mark-64px.png')
                    /= link_to 'Login',

        .page-te
          .container
            = render '/flash_message'

            = yield

    footer.footer-te
      .container
        = render '/footer_text'

    = render '/github_button_script'